language: cpp
dist: bionic
compiler:
  - g++
os:
  - linux
cache:
  directories:
    - /home/travis/.hunter
script:
  - ./codecoverage.sh
after_success:
  # Codecov
  - bash <(curl -s https://codecov.io/bash)

