name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache hunter files
        id: cache-hunter
        uses: actions/cache@v2
        with:
          path: ~/.hunter
          key: ${{ runner.os }}-hunter

      - name: Install dependencies
        run: sudo apt install lcov

      - name: Run coverage
        run: ./codecoverage.sh

