name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci]'

      - name: Install dependencies
        if: ${{ env.CI_SKIP == 'false' }}
        run: sudo apt install -y lcov

      - name: Run coverage
        if: ${{ env.CI_SKIP == 'false' }}
        run: ./codecoverage.sh

      - uses: codecov/codecov-action@v3
        if: ${{ env.CI_SKIP == 'false' }}
        with:
          fail_ci_if_error: true
          verbose: true
